spring:
  mail:
    host: smtp.163.com
    username: 18377122169@163.com
    password: JNgR9333cdQKT5DM
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  web:
    cors:
      origin: 'http://localhost:5173'
      methods: 'GET, POST, PUT, DELETE, OPTIONS'
    verify:
      mail-limit: 60
    flow:
      limit: 50
      period: 3
      block: 30
  application:
    name: iotw
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iotw
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl