spring:
  web:
    cors:
      origin: 'http://localhost:5173'
      methods: 'GET, POST, PUT, DELETE, OPTIONS'
  application:
    name: iotw
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iotw